name: Feature request
description: Suggest a new feature
labels: enhancement
assignees: Mahtwo
body:
  - type: checkboxes
    attributes:
      label: Checklist
      options:
      - label: >
          This isn't a duplicate of an [existing issue](https://github.com/Mahtwo/KHDownloader/issues?q=is%3Aissue%20),
          including closed ones with label "wontfix".
        required: true
      - label: >
          This feature is not present
          on the [latest version](https://github.com/Mahtwo/KHDownloader/releases) of KHDownloader.
        required: true
      - label: You are human and certify this missing feature wasn't hallucinated by AI.
        required: true
  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: When I'm doing [...] it's annoying to do [...]
  - type: textarea
    attributes:
      label: Describe the feature
      description: A clear and concise description of what the feature should be.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    attributes:
      label: Additional informations
      description: Add any other context or screenshots about the feature request here.
