name: Check khd

on:
  # Runs when khd.ps1 or PSScriptAnalyzerSettings.psd1 are changed
  push:
    branches: '**' # Don't run when pushing tags
    paths:
      - 'khd.ps1'
      - 'PSScriptAnalyzerSettings.psd1'
  pull_request:
    paths:
      - 'khd.ps1'
      - 'PSScriptAnalyzerSettings.psd1'

jobs:
  check-khd:
    uses: ./.github/workflows/psscriptanalyzer.yml
    with:
      script-path: ./khd.ps1

  call-refresh-latest-release:
    needs: check-khd
    # Don't refresh release on pull request or not main branch
    if: ${{ github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
    permissions:
      contents: write
    uses: ./.github/workflows/refresh-latest-release.yml
