# Could be merged back into lint.yml when hiding skipped jobs is possible https://github.com/orgs/community/discussions/18001
name: Workflow linters

on:
  # Runs when any file inside .github are changed
  push:
    branches: '**' # Don't run when pushing tags
    paths:
      - '.github/**'
  pull_request:
    paths:
      - '.github/**'

permissions: {}

concurrency:
  # Runs on any commit from upstream repo and only head commit from pull request
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  zizmor:
    name: zizmor
    timeout-minutes: 5
    runs-on: ubuntu-latest # Not ubuntu-slim yet because https://github.com/zizmorcore/zizmor-action/issues/74
    permissions:
      contents: read # Needed by zizmor
      actions: read # Needed by zizmor
    steps:
      - name: Checkout commit
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          sparse-checkout: |
            .github
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@71321a20a9ded102f6e9ce5718a2fcec2c4f70d8 # v0.5.2
        with:
          advanced-security: false
          annotations: true
          persona: pedantic
