name: Linters

on:
  # Runs when any file is changed
  push:
    branches: '**' # Don't run when pushing tags
  pull_request:

permissions:
  contents: read

concurrency:
  # Runs on any commit from upstream repo and only head commit from pull request
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  editorconfig:
    name: EditorConfig
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - name: Checkout commit
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        persist-credentials: false

    - name: Set up editorconfig-checker
      uses: editorconfig-checker/action-editorconfig-checker@840e866d93b8e032123c23bac69dece044d4d84c # v2.2.0

    - name: Run editorconfig-checker
      # GitHub actions annotations does not support terminal color codes
      run: editorconfig-checker -no-color -format github-actions -exclude pester/web/

  zizmor:
    name: zizmor
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed by zizmor
      actions: read # Needed by zizmor
    steps:
      - name: Checkout commit
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          sparse-checkout: |
            .github
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@71321a20a9ded102f6e9ce5718a2fcec2c4f70d8 # v0.5.2
        with:
          advanced-security: false
          annotations: true
          persona: pedantic
