# Could be merged back into lint.yml when hiding skipped jobs is possible https://github.com/orgs/community/discussions/18001
name: PowerShell linters

on:
  # Runs when any PowerShell file beside khd.ps1 are changed
  push:
    branches: '**' # Don't run when pushing tags
    paths:
      - '**.ps[dm]?1'
      - '!khd.ps1'
  pull_request:
    paths:
      - '**.ps[dm]?1'
      - '!khd.ps1'

permissions:
  contents: read

concurrency:
  # Runs on any commit from upstream repo and only head commit from pull request
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  # Check modified paths, which can later be used to filter jobs or steps
  setup-variables:
    name: Setup variables
    timeout-minutes: 5
    runs-on: ubuntu-latest
    # It's not possible to have conditional permissions for now
    permissions:
      contents: read # Needed to see modified files from push event (to checkout)
      pull-requests: read # Needed to see modified files from pull request event
    # Set job outputs to values from filter step
    outputs:
      changed_files: ${{ steps.paths-filter.outputs.changed_files }}
      psscriptanalyzer_all: ${{ steps.paths-filter.outputs.psscriptanalyzer_all }}
      all_files: ${{ steps.all-files.outputs.all_files }}
    steps:
    - name: Checkout commit
      # Pull request does not need checkout to see modified files
      if: ${{ github.event_name == 'push' }}
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        # zizmor: ignore[artipacked] Needed by dorny/paths-filter on push event
        persist-credentials: ${{ github.event_name == 'push' }}

    - name: Setup variables with paths-filter
      uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4
      id: paths-filter
      with:
        # khd.ps1 is already checked in the check khd workflow
        # path syntax is different from workflow paths filter
        # **.ps1 works on any root or nested files but **.ps?(d|m)1 only works on root files
        # **/*.ps?(d|m)1 works for both root and nested files
        filters: |
          changed:
            - added|modified: '**/*.ps?(d|m)1'
            - '!khd.ps1'
          psscriptanalyzer_all:
            - 'PSScriptAnalyzerSettings.psd1'
        # Default value 'some' requires only one pattern to match, so a negated pattern ends up matching
        # everything not-negated while 'every' requires all patterns to match
        predicate-quantifier: 'every'
        list-files: json

    - name: Checkout commit
      # Pull request event needs checkout to setup variable all_files
      if: ${{ steps.paths-filter.outputs.psscriptanalyzer_all == 'true' && github.event_name != 'push' }}
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        persist-credentials: false

    - name: Setup variable all_files
      id: all-files
      if: ${{ steps.paths-filter.outputs.psscriptanalyzer_all == 'true' }}
      # khd.ps1 is already checked in the check khd workflow
      run: echo "all_files=$(git ls-files --full-name -- ':/*.ps1' ':/*.psm1' ':/*.psd1' ':/!khd.ps1' | jq -MRnc '[inputs]')" >> $GITHUB_OUTPUT

  psscriptanalyzer-changed:
    name: PSScriptAnalyzer
    needs: setup-variables
    if: ${{ needs.setup-variables.outputs.psscriptanalyzer_all == 'false' }}
    strategy:
      fail-fast: false
      matrix:
        script-path: ${{ fromJSON(needs.setup-variables.outputs.changed_files) }}
    uses: ./.github/workflows/psscriptanalyzer.yml
    with:
      script-path: ${{ matrix.script-path }}

  psscriptanalyzer-all:
    name: PSScriptAnalyzer all
    needs: setup-variables
    if: ${{ needs.setup-variables.outputs.psscriptanalyzer_all == 'true'}}
    strategy:
      fail-fast: false
      matrix:
        script-path: ${{ fromJSON(needs.setup-variables.outputs.all_files) }}
    uses: ./.github/workflows/psscriptanalyzer.yml
    with:
      script-path: ${{ matrix.script-path }}

  region-endregion-match:
    name: '#region #endregion match'
    needs: setup-variables
    strategy:
      fail-fast: false
      matrix:
        script-path: ${{ fromJSON(needs.setup-variables.outputs.changed_files) }}
    uses: ./.github/workflows/region-endregion-match.yml
    with:
      script-path: ${{ matrix.script-path }}
