name: Run PSScriptAnalyzer
run-name: Run PSScriptAnalyzer on ${{ inputs.script-path }}

on:
  # Runs only when called from another workflow
  workflow_call:
    inputs:
      script-path:
        required: true
        type: string

jobs:
  run-psscriptanalyzer:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ${{ inputs.script-path }} and PSScriptAnalyzerSettings.psd1
      uses: actions/checkout@v6
      with :
        sparse-checkout: |
          ${{ inputs.script-path }}
          PSScriptAnalyzerSettings.psd1
        sparse-checkout-cone-mode: false

    # Adapted from Polly lint workflow under the BSD 3-Clause License. Copyright (c) 2015-2025, App vNext
    # https://github.com/App-vNext/Polly/blob/2b569d48f8e6aa141bf4ecd90728d213d380aeb0/.github/workflows/lint.yml#L67
    - name: Check ${{ inputs.script-path }}
      shell: pwsh -NonInteractive -NoProfile -Command ". '{0}'"
      # Cannot capture summary from -ReportSummary so we run pwsh in another process and capture its output
      # Output can be of type string or array depending on number of lines (string if 0 issues)
      # When Invoke-ScriptAnalyzer is called without a valid path, it does not count as a terminating error
      run: |
        if (-not (Test-Path '${{ inputs.script-path }}')) {
          Write-Output "::error title=PSScriptAnalyzer::Invoke-ScriptAnalyzer: Cannot find path '${{ inputs.script-path }}' because it does not exist."
          exit -1
        }
        $command = @'
          $issues = Invoke-ScriptAnalyzer -Path '${{ inputs.script-path }}' -Settings './PSScriptAnalyzerSettings.psd1' -ReportSummary
          foreach ($issue in $issues) {
            $severity = $issue.Severity.ToString()
            $level = $severity -eq 'Error' ? 'error' : $severity -eq 'Warning' ? 'warning' : 'notice'
            Write-Output "::$level file=$($issue.ScriptName),line=$($issue.Line),col=$($issue.Column),title=PSScriptAnalyzer::$($issue.Message)"
          }
          exit $issues.Count
        '@
        $output = pwsh -NonInteractive -NoProfile -Command $command
        if ($LASTEXITCODE) {
          "### $($output[0])" >> $env:GITHUB_STEP_SUMMARY
          Write-Output $output[1..($output.Count - 1)]
          exit $LASTEXITCODE
        }
