name: Refresh latest release

on:
  # Runs when called from workflow "Check khd" or manually
  workflow_call:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow modifying tags and releases
permissions:
  contents: write

# Allow only one concurrent workflow, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: refresh-latest-release
  cancel-in-progress: true

# Adapted from Xtra workflow : https://github.com/crackededed/Xtra/blob/ea584020d5de37d4c755b0f494c1dac16ade7abc/.github/workflows/android.yml
jobs:
  refresh-latest-release:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - name: Checkout khd.ps1
      uses: actions/checkout@v6
      with :
        # Setting up sparse-checkout automatically adds filter: blob:none
        sparse-checkout: |
          khd.ps1
          .github/RELEASE_TEMPLATE.md
        sparse-checkout-cone-mode: false
        fetch-tags: true
        fetch-depth: 0

    - name: Generate release notes
      # Only use commits that changed khd.ps1 since latest release (:/ means from repo's root)
      run: git log refs/tags/latest..HEAD --oneline --no-decorate -- :/khd.ps1 | tee --append ".github/RELEASE_TEMPLATE.md" "$GITHUB_STEP_SUMMARY"

    - name: Update latest tag
      run: |
        git tag --force latest
        git push --force origin tag latest

    - name: Delete latest release
      continue-on-error: true
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh release delete latest --yes

    - name: Create latest release
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh release create latest --latest --title "Latest" --notes-file ".github/RELEASE_TEMPLATE.md" 'khd.ps1'
