name: Refresh latest release
# Use same run name as workflow_run if available
run-name: ${{ github.event.workflow_run.name || github.workflow }}

on:
  # Runs when workflow "Check khd" has completed (more conditions in job below) or manually
  workflow_run:
    workflows: "Check khd"
    branches: ["main"]
    types: completed
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow modifying tags and releases
permissions:
  contents: write

# Allow only one concurrent workflow, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: refresh-latest-release

# Adapted from Xtra workflow : https://github.com/crackededed/Xtra/blob/ea584020d5de37d4c755b0f494c1dac16ade7abc/.github/workflows/android.yml
jobs:
  refresh-latest-release:
    # If "Check khd" succeeded on push or workflow started manually
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout khd.ps1
      uses: actions/checkout@v6
      with :
        # Setting up sparse-checkout automatically adds filter: blob:none
        sparse-checkout: khd.ps1
        sparse-checkout-cone-mode: false
        fetch-tags: true
        fetch-depth: 0

    - name: Generate release notes
      # Only use commits that changed khd.ps1 since latest release (:/ means from repo's root)
      # Use $RUNNER_TEMP in case we later add a notes.txt file in the repo
      run: git log refs/tags/latest..HEAD --oneline --no-decorate -- :/khd.ps1 > "$RUNNER_TEMP/notes.txt"

    - name: Update latest tag
      run: |
        git tag --force latest
        git push --force origin tag latest

    - name: Delete latest release
      continue-on-error: true
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh release delete latest --yes

    - name: Create latest release
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh release create latest --latest --title "Latest" --notes-file "$RUNNER_TEMP/notes.txt" 'khd.ps1'
