name: Create release
run-name: Create ${{ inputs.version-type }} release

on:
  # Runs only manually
  workflow_dispatch:
    inputs:
      version-type:
        default: patch
        # Descriptions are shown on a single line, with wrapping if needed
        # New lines are replaced with space
        description: |
          Corresponds to semantic versioning major.minor.patch.
          major is breaking changes,
          minor is backward-compatible new features,
          patch is backward-compatible bug fixes.
        options:
          - major
          - minor
          - patch
        required: true
        type: choice

permissions:
  contents: read # Required for check-khd

# Allow only one concurrent workflow per commit,
# since it wouldn't make sense for a single commit to be multiple versions
concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  # Stopping in progress may causes discrepancies, for example a version present on GitHub but not PowerShell Gallery
  cancel-in-progress: false

env:
  RELEASE_NOTES_PATH: .github/RELEASE_TEMPLATE.md

jobs:
  check-khd:
    name: Check khd
    uses: ./.github/workflows/release.yml

  create-release:
    name: Create
    needs: check-khd
    timeout-minutes: 5
    environment: deploy
    runs-on: ubuntu-slim
    # Sets permissions of github.token
    permissions:
      contents: write # Delete and create tag/release
    steps:
    - name: Checkout khd.ps1
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with :
        # Setting up sparse-checkout automatically adds filter: blob:none
        sparse-checkout: |
          khd.ps1
          ${{ env.RELEASE_NOTES_PATH }}
        sparse-checkout-cone-mode: false
        fetch-tags: true
        fetch-depth: 0
        persist-credentials: false

    - name: Setup variables
      id: variables
      env:
        VERSION_TYPE: ${{ inputs.version-type }}
      run: |
        # There is no "number of occurences" in the pattern of --match, i.e. 1foo.2bar.3.4 would be valid
        # Therefore this is the best pattern that can be done with future-proofing for 2 or more digits
        version_previous="$(git describe --tags --abbrev=0 --match '[0-9]*.[0-9]*.[0-9]*')"
        [ -z "$version_previous" ] && exit 1
        echo "version_previous=$version_previous" >> "$GITHUB_OUTPUT"
        echo "Previous version: $version_previous" >> "$GITHUB_STEP_SUMMARY"

        IFS=. read -r major minor patch <<< "$version_previous"
        case "$VERSION_TYPE" in
          major)
            version="$((major+1)).0.0"
            ;;
          minor)
            version="$major.$((minor+1)).0"
            ;;
          patch)
            version="$major.$minor.$((patch+1))"
            ;;
        esac
        echo "version=$version" >> "$GITHUB_OUTPUT"
        echo "New version: $version" >> "$GITHUB_STEP_SUMMARY"

    - name: Remove TODOs from khd.ps1
      # First command removes lines starting with # TODO
      # Second command removes only the text from # TODO to end of line
      run: sed -i -e '/^\s*#\s*todo/Id' -e 's/\s*#\s*todo.*//I' khd.ps1

    - name: Replace 0.0.0-placeholder with ${{ env.VERSION }} in khd.ps1
      env:
        VERSION: ${{ steps.variables.outputs.version }}
      # Update-PSScriptFileInfo breaks the header section (help unparsable, removing SPDX, ...)
      # New-PSScriptFileInfo outputs every properties including those with no value specified
      run: sed -i "s/0.0.0-placeholder/$VERSION/I" khd.ps1

    - name: Generate release notes
      env:
        VERSION_PREVIOUS: ${{ steps.variables.outputs.version_previous }}
      # Only use commits that changed khd.ps1 since latest release (:/ means from repo's root)
      # If no new changes to khd.ps1, append "None"
      run: |
        changes="$(git log "refs/tags/$VERSION_PREVIOUS..HEAD" --oneline --no-decorate -- ':/khd.ps1')"
        {
          echo "# Changes since $VERSION_PREVIOUS"
          echo "${changes:-None}"
        } >> "$RELEASE_NOTES_PATH"
        cat "$RELEASE_NOTES_PATH" >> "$GITHUB_STEP_SUMMARY"

    - name: Create GitHub release ${{ env.VERSION }}
      env:
        GH_TOKEN: ${{ github.token }}
        VERSION: ${{ steps.variables.outputs.version }}
      # Will automatically create the tag
      # When the tag doesn't already exist, release will be a draft by default
      run: gh release create "$VERSION" --latest --title "$VERSION" --draft=false --notes-file "$RELEASE_NOTES_PATH" 'khd.ps1'

      # It's not clear if --draft=false has no effect with release create or a bug causes releases to sometimes still be draft
    - name: Publish GitHub release ${{ env.VERSION }}
      env:
        GH_TOKEN: ${{ github.token }}
        VERSION: ${{ steps.variables.outputs.version }}
      run: gh release edit "$VERSION" --draft=false

    - name: Publish PowerShell Gallery release ${{ env.VERSION }}
      env:
        PSGALLERY_TOKEN: ${{ secrets.PSGALLERY_TOKEN }}
        VERSION: ${{ steps.variables.outputs.version }}
      shell: pwsh -NonInteractive -NoProfile -Command ". '{0}'"
      run: Publish-Script -LiteralPath khd.ps1 -Repository PSGallery -NuGetApiKey $env:PSGALLERY_TOKEN
